apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-live-mediamtx-config
  namespace: jitsi-overlord
data:
  mediamtx.yml: |
    logLevel: info
    api: yes
    apiAddress: :9997
    authMethod: internal
    authInternalUsers:
      - user: any
        pass: ""
        permissions:
          - action: publish
          - action: read
          - action: playback
          - action: api
    rtmp: yes
    rtmpAddress: :1935
    hls: yes
    hlsAddress: :8888
    hlsAlwaysRemux: yes
    paths:
      all_others:
        source: publisher
